Traceback (most recent call last):
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kmaull\Anaconda3\envs\soarsbook\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
top10_most_cites.index = top10_most_cites.doi
top10_most_cites = top10_most_cites.drop(['doi'], axis=1)
top10_merged = \
    top10_most_cites.merge(df_citations, left_index=True, right_index=True)\
            [['cites', 'citation']]

top10_merged.index.set_names('DOI')
with open("../outputs/top10_pubs_simple.md", "w", encoding='utf-8') as fo:
    fo.write( 
        top10_merged.to_markdown(index=True)
    )

top10_merged.to_csv("../outputs/top10_pubs_simple.csv", index=False)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [1;32m~\Anaconda3\envs\soarsbook\lib\site-packages\pandas\compat\_optional.py:142[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    141[0m [38;5;28;01mtry[39;00m:
[1;32m--> 142[0m     module [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mimport_module[49m[43m([49m[43mname[49m[43m)[49m
[0;32m    143[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [1;32m~\Anaconda3\envs\soarsbook\lib\importlib\__init__.py:127[0m, in [0;36mimport_module[1;34m(name, package)[0m
[0;32m    126[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m--> 127[0m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[38;5;241;43m.[39;49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

File [1;32m<frozen importlib._bootstrap>:1030[0m, in [0;36m_gcd_import[1;34m(name, package, level)[0m

File [1;32m<frozen importlib._bootstrap>:1007[0m, in [0;36m_find_and_load[1;34m(name, import_)[0m

File [1;32m<frozen importlib._bootstrap>:984[0m, in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;31mModuleNotFoundError[0m: No module named 'tabulate'

During handling of the above exception, another exception occurred:

[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn [17], line 10[0m
[0;32m      7[0m top10_merged[38;5;241m.[39mindex[38;5;241m.[39mset_names([38;5;124m'[39m[38;5;124mDOI[39m[38;5;124m'[39m)
[0;32m      8[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([38;5;124m"[39m[38;5;124m../outputs/top10_pubs_simple.md[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m, encoding[38;5;241m=[39m[38;5;124m'[39m[38;5;124mutf-8[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m fo:
[0;32m      9[0m     fo[38;5;241m.[39mwrite( 
[1;32m---> 10[0m         [43mtop10_merged[49m[38;5;241;43m.[39;49m[43mto_markdown[49m[43m([49m[43mindex[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m     11[0m     )
[0;32m     13[0m top10_merged[38;5;241m.[39mto_csv([38;5;124m"[39m[38;5;124m../outputs/top10_pubs_simple.csv[39m[38;5;124m"[39m, index[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

File [1;32m~\Anaconda3\envs\soarsbook\lib\site-packages\pandas\core\frame.py:2841[0m, in [0;36mDataFrame.to_markdown[1;34m(self, buf, mode, index, storage_options, **kwargs)[0m
[0;32m   2839[0m kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mtablefmt[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mpipe[39m[38;5;124m"[39m)
[0;32m   2840[0m kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mshowindex[39m[38;5;124m"[39m, index)
[1;32m-> 2841[0m tabulate [38;5;241m=[39m [43mimport_optional_dependency[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mtabulate[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m   2842[0m result [38;5;241m=[39m tabulate[38;5;241m.[39mtabulate([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   2843[0m [38;5;28;01mif[39;00m buf [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [1;32m~\Anaconda3\envs\soarsbook\lib\site-packages\pandas\compat\_optional.py:145[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    143[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m    144[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[1;32m--> 145[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[0;32m    146[0m     [38;5;28;01melse[39;00m:
[0;32m    147[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

[1;31mImportError[0m: Missing optional dependency 'tabulate'.  Use pip or conda to install tabulate.
ImportError: Missing optional dependency 'tabulate'.  Use pip or conda to install tabulate.

